# Generated by Django 2.0.1 on 2018-01-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_like', models.IntegerField()),
                ('date', models.DateField()),
                ('tags', models.CharField(choices=[('Cats', 'Cats'), ('Code', 'Code'), ('Design', 'Design')], default='Code', max_length=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.Asset')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.Content')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
